version: '3.5'
services:
  influxdb:
    image: influxdb:latest
    restart: unless-stopped
    ports:
      - '8086:8086'
    volumes:
      - /var/local/influx-data:/var/lib/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=${INFLUXDB_USERNAME}
      - DOCKER_INFLUXDB_INIT_PASSWORD=${INFLUXDB_PASSWORD}
      - DOCKER_INFLUXDB_INIT_ORG=home
      - DOCKER_INFLUXDB_INIT_BUCKET=telegraf
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=${INFLUXDB_TOKEN}
  grafana:
    image: grafana/grafana:latest
    restart: unless-stopped
    ports:
      - '3000:3000'
    volumes:
      - /var/local/grafana-data:/var/lib/grafana
    depends_on:
      - influxdb
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_USERNAME}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}
  influx_backup:
    build: ./influx-backup
    restart: unless-stopped
    depends_on:
      - influxdb
    environment:
      - INFLUXDB_TOKEN=${INFLUXDB_TOKEN}
      - S3_BUCKET=${S3_BUCKET}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
      - DATABASE_HOST=influxdb
      - DATABASE=telegraf
  mqtt:
    container_name: mqtt
    image: eclipse-mosquitto:latest
    restart: unless-stopped
    depends_on:
      - influxdb
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - /home/pi/smarthouse/conf/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - /var/local/mqtt-data:/mosquitto/data/
  telegraf:
    container_name: telegraf
    image: telegraf:latest
    restart: unless-stopped
    depends_on:
      - mqtt
      - influxdb
    environment:
      - INFLUX_TOKEN=${INFLUXDB_TOKEN}
    volumes:
      - /home/pi/smarthouse/conf/telegraf.conf:/etc/telegraf/telegraf.conf
  ble-mqtt:
    build: ./ble-sensor
    restart: unless-stopped
    volumes:
      - /home/pi/smarthouse/conf/ble-mqtt.ini:/conf/mqtt.ini
      - /home/pi/smarthouse/conf/ble-devices.ini:/conf/devices.ini
    network_mode: "host"
    privileged: true
  nest-flask:
    build: ./nest-flask
    restart: unless-stopped
    depends_on:
      - influxdb
    ports:
      - "5000:5000"
    volumes:
      - /home/pi/smarthouse/nest-flask/:/app
    environment:
      - CLIENT_ID=${NEST_CLIENT_ID}
      - CLIENT_SECRET=${NEST_CLIENT_SECRET}
      - CODE=${NEST_CODE}
      - REFRESH_TOKEN=${NEST_REFRESH_TOKEN}
      - DEVICE_NAME=${NEST_DEVICE_NAME}
