{
 "title": "Tablet",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "5m",
 "panels": [
  {
   "title": "Tarifa atual",
   "type": "status-history",
   "gridPos": { "h": 3, "w": 10, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "query": "from(bucket: \"telegraf\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"p1meter\")\n  |> filter(fn: (r) => r[\"_field\"] == \"actual_tarif_group\")\n  |> drop(fn: (column) => column =~ /(host|topic)/)\n  |> aggregateWindow(every: 1h, fn: max)"
    }
   ]
  },
  {
   "title": "Consumo",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "query": "from(bucket: \"telegraf\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"p1meter\")\n  |> filter(fn: (r) => r[\"_field\"] == \"actual_consumption\")\n  |> drop(fn: (column) => column =~ /(host|topic)/)\n  |> aggregateWindow(every: 1m, fn: max)"
    },
    {
     "query": "from(bucket: \"telegraf\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"p1meter\")\n  |> filter(fn: (r) => r[\"_field\"] == \"gas_meter_m3\")\n  |> drop(fn: (column) => column =~ /(host|topic)/)\n  |> aggregateWindow(every: 1m, fn: max)\n  |> map(fn: (r) => ({ r with _value: r._value / 1000.0 }))\n  |> derivative(unit: 1m)\n  "
    }
   ]
  },
  {
   "title": "Consumo atual",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"telegraf\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"p1meter\")\n  |> filter(fn: (r) => r[\"_field\"] == \"actual_consumption\")\n  |> tail(n: 1)"
    },
    {
     "query": "from(bucket: \"telegraf\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"p1meter\")\n  |> filter(fn: (r) => r[\"_field\"] == \"gas_meter_m3\")\n  |> map(fn: (r) => ({ r with _value: r._value / 1000.0 }))\n  |> aggregateWindow(every: 30m, fn: max)\n  |> fill(column: \"_value\", usePrevious: true)\n  |> derivative(unit: 30m)\n  |> tail(n: 1)"
    }
   ]
  },
  {
   "title": "Custo Energia €",
   "type": "status-history",
   "gridPos": { "h": 5, "w": 10, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "targets": [
    {
     "query": "from(bucket: \"sensors-downsampled\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"p1meter\")\n  |> filter(fn: (r) => r[\"_field\"] == \"gas_meter_m3\")\n  |> map(fn: (r) => ({ r with _value: r._value / 1000.0 }))\n  |> aggregateWindow(every: 1d, fn: last)\n  |> derivative(unit: 1d)\n  |> map(fn: (r) => ({ r with _value: r._value * 0.807 }))"
    },
    { "expression": "$A + $B", "type": "math" }
   ]
  },
  {
   "title": "Casa",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 10, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"telegraf\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"thermometer\")\n  |> filter(fn: (r) => r[\"_field\"] == \"temperature\")\n  |> filter(fn: (r) => r[\"sensor\"] == \"quarto\")\n  |> aggregateWindow(every: 5m, fn: mean)\n  |> map(fn: (r) => ({ _value:r._value, _time:r._time, _field:\"quarto\" }))\n  |> tail(n:1)"
    },
    {
     "query": "from(bucket: \"telegraf\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"thermometer\")\n  |> filter(fn: (r) => r[\"_field\"] == \"temperature\")\n  |> filter(fn: (r) => r[\"sensor\"] == \"sala\")\n  |> aggregateWindow(every: 5m, fn: mean)\n  |> map(fn: (r) => ({ _value:r._value, _time:r._time, _field:\"escritorio\" }))\n  |> tail(n:1)"
    },
    {
     "query": "from(bucket: \"telegraf\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"thermometer\")\n  |> filter(fn: (r) => r[\"_field\"] == \"temperature\")\n  |> filter(fn: (r) => r[\"sensor\"] == \"banheiro\")\n  |> aggregateWindow(every: 5m, fn: mean)\n  |> map(fn: (r) => ({ _value:r._value, _time:r._time, _field:\"banheiro\" }))\n  |> tail(n:1)"
    },
    {
     "query": "from(bucket: \"telegraf\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"thermometer\")\n  |> filter(fn: (r) => r[\"_field\"] == \"temperature\")\n  |> filter(fn: (r) => r[\"sensor\"] == \"varanda\")\n  |> aggregateWindow(every: 5m, fn: mean)\n  |> map(fn: (r) => ({ _value:r._value, _time:r._time, _field:\"varanda\" }))\n  |> tail(n:1)"
    }
   ]
  },
  {
   "title": "Nest",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 3, "x": 15, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"telegraf\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"nest\")\n  |> filter(fn: (r) => r[\"_field\"] == \"temperature\")\n  |> tail(n:1)"
    },
    {
     "query": "from(bucket: \"telegraf\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"nest\")\n  |> filter(fn: (r) => r[\"_field\"] == \"setpoint\")\n  |> tail(n:1)"
    }
   ]
  },
  {
   "title": "Varanda",
   "type": "status-history",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "from(bucket: \"telegraf\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"thermometer\")\n  |> filter(fn: (r) => r[\"_field\"] == \"temperature\")\n  |> filter(fn: (r) => r[\"sensor\"] == \"varanda\")\n  |> aggregateWindow(every: 1d, fn: max)\n  |> map(fn: (r) => ({ _value:r._value, _time:r._time, _field:\"-\" }))\n  |> limit(n: 3)\n"
    },
    {
     "query": "from(bucket: \"telegraf\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"thermometer\")\n  |> filter(fn: (r) => r[\"_field\"] == \"temperature\")\n  |> filter(fn: (r) => r[\"sensor\"] == \"varanda\")\n  |> aggregateWindow(every: 1d, fn: min)\n  |> map(fn: (r) => ({ _value:r._value, _time:r._time, _field:\" \" }))\n  |> limit(n: 3)"
    }
   ]
  },
  {
   "title": "Nest Status",
   "type": "status-history",
   "gridPos": { "h": 5, "w": 10, "x": 0, "y": 8 },
   "targets": [
    {
     "query": "from(bucket: \"telegraf\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"nest\")\n  |> filter(fn: (r) => r[\"_field\"] == \"status\")\n  |> aggregateWindow(every: 1h, fn: last)"
    },
    {
     "query": "from(bucket: \"telegraf\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"nest\")\n  |> filter(fn: (r) => r[\"_field\"] == \"eco\")\n  |> aggregateWindow(every: 1h, fn: last)"
    }
   ]
  }
 ]
}